### ISSUE TITLE
Could not resolve project :react-native-interactable.

### ISSUE THREAD

**Issue by Alan911Black** [wix/react-native-interactable#230]
Hi,
dose anyone know how to solve this? 
![error](https://user-images.githubusercontent.com/31937768/45271709-c54e4780-b45d-11e8-9bd7-0f8a5c475934.jpg)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-interactable@0.1.10 postinstall: `ln -sf lib/{ios,android} .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-interactable@0.1.10 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output
above.

i am also getting this error when trying to link

PS C:\Test\Projectwow\client> react-native link react-native-interactable
Scanning folders for symlinks in C:\Test\Projectwow\client\node_modules (24ms)
{ Error: Cannot find module 'C:\Test\Projectwow\client\node_modules\react-native-interactable\package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getRNPMConfig (C:/Test/Projectwow/client/node_modules/react-native/local-cli/core/index.js:53:3)
    at Object.getDependencyConfig (C:/Test/Projectwow/client/node_modules/react-native/local-cli/core/index.js:115:18)
    at deps.reduce (C:/Test/Projectwow/client/node_modules/react-native/local-cli/link/getDependencyConfig.js:16:24)
    at Array.reduce (<anonymous>)
    at getDependencyConfig (C:/Test/Projectwow/client/node_modules/react-native/local-cli/link/getDependencyConfig.js:13:15)
    at Object.link (C:/Test/Projectwow/client/node_modules/react-native/local-cli/link/link.js:131:24) code: 'MODULE_NOT_FOUND' }
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
PS C:\Test\Projectwow\client>

thanks

**Comment by chakrihacker** [comment]
Which operating system are you using??

**Comment by MrCreeper1008** [comment]
Android, probably. If that's the case, go to ```android/settings.gradle``` and change 
```project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/android')```
to
```project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/lib/android')```.

It seems like the folders for native codes, ```/ios``` and ```/android``` that is, have been moved to ```/lib```.

**Comment by liri321** [comment]
I switched to yarn and I was able to successfully install react-native-interactable
