### ISSUE TITLE
[Android] Error while updating property 'transform' of a view managed by: RCTView. Cannot set 'scaleX' to Float.NaN

### ISSUE THREAD

**Issue by addingama** [wix/react-native-interactable#284]
I'm having trouble after upgrading my RN project to RN 0.59.0.

I got this error.
<img width="345" alt="image" src="https://user-images.githubusercontent.com/2896774/59653083-26603400-91c3-11e9-8471-36414dcaeac3.png">

This is the implementation on my app

```
<Interactable.View
              verticalOnly={true}
              ref='panel'
              snapPoints={[
                {y: 0, id: 'top', index: 0},
                {y: MIN_LOC_SIZE, id: 'bottom', index: 1},
                {y: (-1*INIT_HEIGHT)+extraHeight, id: 'location_search', index: 2}
              ]}
              alertAreas={[{id: 'nearBottom', influenceArea: {top: MIN_LOC_SIZE-20, bottom: MIN_LOC_SIZE+20}}]}
              scrollEventThrottle={16}
              frictionAreas={isIphone ? null : [{damping: 1.0, influenceArea: {top: MIN_LOC_SIZE-1}}]}
              dragWithSpring={isIphone ? null : {tension: 2000, damping: 0.5}}
              animatedNativeDriver={true}
              boundaries={
               {
                  top: this.state.searchActive ? -1*INIT_HEIGHT : MIN_LOC_SIZE-1,
                  bottom: 0,
                }
              }
              dragToss={.1}
              onSnap={this.onSnap}
              onAlert={this.onAlert}
            //  onScroll={(event) => console.log(event.nativeEvent.y)}
              animatedValueY={this._deltaY}
              showsVerticalScrollIndicator={false}
              style={{backgroundColor: standards.backgroundColor}}
            >
              <SearchLocationBar
                heightL={SEARCH_RESULTS_HEIGHT}
                heightS={SEARCH_BAR_HEIGHT}
                heightBase={SEARCH_BAR_BASE_HEIGHT}
                searchActive={this.state.searchActive}
                deactivateSearch={this._deactivateSearch}
                activateSearch={this._activateSearch}
                />
              <SearchVenueList
                // hval={null}
                hval={hval}
                sval={sval}
                canScroll={this.state.canScroll}
                onScroll={this.onScroll} />
            </Interactable.View>

```

This is the full stack trace

```
ava.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
    at android.view.View.sanitizeFloatPropertyValue(View.java:16979)
    at android.view.View.sanitizeFloatPropertyValue(View.java:16953)
    at android.view.View.setScaleX(View.java:16342)
    at com.facebook.react.uimanager.BaseViewManager.setTransformProperty(BaseViewManager.java:220)
    at com.facebook.react.uimanager.BaseViewManager.setTransform(BaseViewManager.java:72)
    at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:218)
    at com.facebook.react.views.view.ReactViewManager.setTransform(ReactViewManager.java:36)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:136)
    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:345)
    at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:99)
    at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:545)
    at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:414)
    at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:392)
    at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:117)
    at com.wix.interactable.InteractableViewManager$InteractionEventEmitter.onAnimatedEvent(InteractableViewManager.java:195)
    at com.wix.interactable.InteractableView.onAnimationFrame(InteractableView.java:112)
    at com.wix.interactable.physics.PhysicsAnimator.doFrame(PhysicsAnimator.java:34)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:693)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:136)
    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:345)
    at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:99)
    at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:545)
    at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:414)
    at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:392)
    at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:117)
    at com.wix.interactable.InteractableViewManager$InteractionEventEmitter.onAnimatedEvent(InteractableViewManager.java:195)
    at com.wix.interactable.InteractableView.onAnimationFrame(InteractableView.java:112)
    at com.wix.interactable.physics.PhysicsAnimator.doFrame(PhysicsAnimator.java:34)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:693)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'transform' of a view managed by: RCTView
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:95)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:136)
    at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:345)
    at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:99)
    at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:545)
    at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:414)
    at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:392)
    at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:117)
    at com.wix.interactable.InteractableViewManager$InteractionEventEmitter.onAnimatedEvent(InteractableViewManager.java:195)
    at com.wix.interactable.InteractableView.onAnimationFrame(InteractableView.java:112)
    at com.wix.interactable.physics.PhysicsAnimator.doFrame(PhysicsAnimator.java:34)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
    at android.view.Choreographer.doCallbacks(Choreographer.java:761)
    at android.view.Choreographer.doFrame(Choreographer.java:693)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Any clue on how to fix this?

**Comment by ketanvault** [comment]
Me too have the same issue. Please provide solution for this.

**Comment by PMakWANordics** [comment]
Faced with the same issue

**Comment by Nargle30** [comment]
Same issue on emulator, on the real device it works well

**Comment by aminshariatmadar** [comment]
same issue on the sumsung a7. and in the a3 it works correctly.

**Comment by Nargle30** [comment]
As I noticed it depends on Android version.

**Comment by MehmetKaplan** [comment]
Any updates on this so far?

**Comment by mtiziano** [comment]
Same issue on emulator

**Comment by mtiziano** [comment]
resolved my problem, i was interpolating **transform** rotation with Animated.Value()

`style={{ transform: [ {rotate: angle.interpolate( ... `

`animated.value` was correctly initialized with a number `Animated.Value(0) `

but then for mistake it was updating with a **string** in componentDidMount `angle.setValue('off')`
