### ISSUE TITLE
Error on npx react-native run-android, ENOTDIR

### ISSUE THREAD

**Issue by JakeHadley** [wix/react-native-interactable#305]
I'm getting this very frustrating error on windows with running the command in the title:
```
error ENOTDIR invalid cwd C:\dev\LoganTransitApp\node_modules\react-native-interactable\android. Run CLI with --verbose flag for more details.
Error: ENOTDIR invalid cwd C:\dev\LoganTransitApp\node_modules\react-native-interactable\android
    at GlobSync._readdirError (C:\dev\LoganTransitApp\node_modules\glob\sync.js:324:21)
    at GlobSync._readdir (C:\dev\LoganTransitApp\node_modules\glob\sync.js:290:10)
    at GlobSync._processGlobStar (C:\dev\LoganTransitApp\node_modules\glob\sync.js:350:22)
    at GlobSync._process (C:\dev\LoganTransitApp\node_modules\glob\sync.js:130:10)
    at new GlobSync (C:\dev\LoganTransitApp\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (C:\dev\LoganTransitApp\node_modules\glob\sync.js:26:10)
    at findManifest (C:\dev\LoganTransitApp\node_modules\@react-native-community\cli-platform-android\build\config\findManifest.js:38:40)
    at Object.dependencyConfig (C:\dev\LoganTransitApp\node_modules\@react-native-community\cli-platform-android\build\config\index.js:106:135)
    at C:\dev\LoganTransitApp\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\index.js:67:61
    at Array.reduce (<anonymous>)
```
What in the world is wrong here?

**Comment by ninacoder-info** [comment]
same problem for me :(
