### ISSUE TITLE
Crash on android when dragging is initiated from a view with prop pointerEvents="box-none"

### ISSUE THREAD

**Issue by FakeYou** [wix/react-native-interactable#53]
When `Interactable.View` contains a view with the prop `pointerEvents="box-none"` the application will crash when dragging is started from this view.

I've created a [repo which reproduces this issue](https://github.com/FakeYou/react-native-interactable-crash). Specifically [this line](https://github.com/FakeYou/react-native-interactable-crash/blob/master/src/App.js#L14) will crash the app.

the error log of the crash looks like this:
```
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.interactablecrash, PID: 15408
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.wix.interactable.physics.PhysicsBehavior.setAnchorPoint(android.graphics.PointF)' on a null object reference
AndroidRuntime: 	at com.wix.interactable.InteractableView.handleTouch(InteractableView.java:218)
AndroidRuntime: 	at com.wix.interactable.InteractableView.onTouchEvent(InteractableView.java:197)
AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:10023)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2626)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2654)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:414)
AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3064)
AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:376)
AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:10243)
AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6321)
AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6373)
AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:615)
AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
04-05 19:06:17.304   893  3451 W ActivityManager:   Force finishing activity com.interactablecrash/.MainActivity
```

---

On another note, it seems that having the `Interactable.View` as the root of your project (the component you pass to `registerComponent`) will crash the app when dragging anywhere. But I don't think many people would structure their app like that.

**Comment by ButtersHub** [comment]
Hi @FakeYou, this bug was fixed yesterday, just update your master branch and it should work. 
Please update us if it works for you.

**Comment by FakeYou** [comment]
After updating to the master branch and building a new apk I can confirm that it's working for me. Thank you.
